export const SET_EMPLOYEE_LOADING_START = 'SET_EMPLOYEE_LOADING_START';

export const SET_EMPLOYEE_LOADING_STOP = 'SET_EMPLOYEE_LOADING_STOP';

export const SET_EMPLOYEES_DATA = 'SET_EMPLOYEES_DATA';
